spring.application.name: ribbon-consumer
server.port: 5555
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
zuul.routes.api-a.path: /api-a/**
zuul.routes.api-a.serviceId: compute-service

