server:
  port: 8761  #指定该Eureka实例的端口
  
eureka:
   instance:
        hostname: lcoalhost
   client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
